### ISSUE TITLE
Changing <img> element to NextJS's <Image> element

### ISSUE THREAD

**Issue by rohitmondal03** [firecamp-dev/website#10]
During build process, the `<img />` element is giving warning

#  Solution 
Change it to NextJS's `<Image />` element
![Screenshot (113)](https://github.com/firecamp-dev/website/assets/107113353/871e40a5-3f2b-47ac-8d5e-b905fa66c0f6)

**Comment by Nick-h4ck3r** [comment]
I would like to take on this issue.

**Comment by Nishchit14** [comment]
@Nick-h4ck3r you can fix it.

**Comment by rohitmondal03** [comment]
@Nishchit14 is this issue open ?

**Comment by Nishchit14** [comment]
@rohitmondal03 yes, you can fix it.
