### ISSUE TITLE
Pricing Page Improvement

### ISSUE THREAD

**Issue by Nishchit14** [firecamp-dev/website#15]
The preview of the pricing page is 

<img width="834" alt="image" src="https://github.com/firecamp-dev/website/assets/5078921/76d3efe0-8257-4cb1-8bd9-00189b46c40a">

**Comment by Virtual4087** [comment]
You want it to look like this?

**Comment by Kritik-J** [comment]
@Nishchit14 please assign this to me

**Comment by shreya-gr** [comment]
@Kritik-J assigned to you. looking forward to PR.
