### ISSUE TITLE
Responsive Navbar

### ISSUE THREAD

**Issue by Nishchit14** [firecamp-dev/website#6]
The navbar is not responsive. when we open the website on a mobile device it shows a horizontal scrollbar.

<img width="516" alt="image" src="https://github.com/firecamp-dev/website/assets/5078921/98de9689-c6bb-4d42-9966-5856f68b5644">

**Comment by rohitmondal03** [comment]
@Nishchit14 can you assign me this issue ?

**Comment by Nishchit14** [comment]
@rohitmondal03 you can work on it.

**Comment by rohitmondal03** [comment]
> @rohitmondal03 you can work on it.

Can you please mention it under hacktoberfest label !!!!

**Comment by rohitmondal03** [comment]
@Nishchit14 can I know how should I add the navbar in small screens ? Should I use hamburger menu or something else ?

**Comment by Nishchit14** [comment]
@rohitmondal03 I think hamburger would be fine, we're using this [template](https://github.com/shadcn-ui/taxonomy) if you can get some help from here.

**Comment by rohitmondal03** [comment]
ok I'll then required components from shadcn then

**Comment by Nishchit14** [comment]
@rohitmondal03 whatever is good for you, you can use from shadcn or use custom one.
